// app/layout.tsx
import { Metadata } from 'next';
import Providers from './providers';
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "ACE RnR reward",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({
  
  children,
}: {
  
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body>
        <main>
        <Providers>
            {children}
        </Providers>
        </main>
      </body>
    </html>
  );
}